### ISSUE TITLE
Plans to support 6.x

### ISSUE THREAD

**Issue by botzill** [elastic/ansible-elasticsearch#394] opened 2017-10-13 08:32 UTC
Hi.

I tried to install 6.x version using the following settings:
```
es_version: "6.0.0-rc1"
es_major_version: "6.x-prerelease"
```

but seems to not be able to install it, es does not start.
I'm testing this on Debian.
Any plans to support 6.x version ?

**Comment by kakoni** [comment] 2017-11-15 11:13
elasticsearch-systemd-pre-exec was removed in 6.x (https://github.com/elastic/elasticsearch/commit/9d8f11dc27c1fc2057e7ea5a82c0a5f364f5e8ce#diff-4a4d0518983ac4a587c14d372df2e241) meaning systemd scripts would fail (https://github.com/elastic/ansible-elasticsearch/blob/23abae8c671d0812a740dead6a418441acc63213/templates/systemd/elasticsearch.j2#L20)

**Comment by toddlers** [comment] 2017-12-04 08:09
Fixed it, there are not too many changes to adapt this ansible role for ES 6.x

**Comment by kakoni** [comment] 2017-12-04 08:22
Theres PR already, https://github.com/elastic/ansible-elasticsearch/pull/397

**Comment by Crazybus** [comment] 2018-01-31 12:40
Duplicate of https://github.com/elastic/ansible-elasticsearch/issues/407

**Closed by Crazybus** 2018-01-31 12:40 UTC
