### ISSUE TITLE
Plugins don't install "Can't open //etc/default/elasticsearch"

### ISSUE THREAD

**Issue by bhcopeland** [elastic/ansible-elasticsearch#147] opened 2016-09-06 16:02 UTC
So, I updated my repo and updated to 2.4.0. I ran the playbook to update:

```
ASK [ansible-elasticsearch : Install elasticsearch plugins] *******************
task path: ansible-playbooks/roles/ansible-elasticsearch/tasks/elasticsearch-plugins.yml:34
basic
skipping: [elk.x.org] => (item={u'version': u'latest', u'plugin': u'mobz/elasticsearch-head'})  => {"changed": false, "item": {"plugin": "mobz/elasticsearch-head", "version": "latest"}, "skip_reason": "Conditional check failed", "skipped": true}
skipping: [elk.x.org] => (item={u'version': u'latest', u'plugin': u'lmenezes/elasticsearch-kopf'})  => {"changed": false, "item": {"plugin": "lmenezes/elasticsearch-kopf", "version": "latest"}, "skip_reason": "Conditional check failed", "skipped": true}
```

Upon looking into it, I went to run /usr/share/elasticsearch/bin/plugin, and got:

```
/usr/share/elasticsearch/bin/plugin: 49: .: Can't open //etc/default/elasticsearch
```

I looked in the playbook and saw:

```
- name: Delete Default Environment File
  file: dest=/etc/default/elasticsearch state=absent
  when: ansible_os_family == 'Debian'
```

**Comment by barryib** [comment] 2016-09-06 19:00
@bhcopeland can you please run your playbook in verbose and share your error?

Normally, these following env vars are set during plugin management:
```yml
  environment:
    CONF_DIR: "{{ conf_dir }}"
    ES_INCLUDE: "{{ instance_default_file }}"
```
So wont (normally) have this error:
``/usr/share/elasticsearch/bin/plugin: 49: .: Can't open //etc/default/elasticsearch``

If you want to run plugin installation manually, you have to export those environment variables.

For the task you're referring to (**Delete Default Environment File**), its normal. The default ``/etc/default/elasticsearch`` is removed and replaced by a custom one (see [here](https://github.com/elastic/ansible-elasticsearch/blob/master/tasks/elasticsearch-config.yml#L25))

**Comment by bhcopeland** [comment] 2016-09-07 12:47
Thanks Barry.

You are right, the modified environment is in place, I was running it manually, because my plugins are not installing with the playbook. When I run the playbook, I get Conditional check failed.

https://gist.github.com/b6ca5e3f3ee93c5a15f211e399018a28

https://gist.github.com/d731d29ddb7e146906d46fb7a293343a

```
TASK [ansible-elasticsearch : Remove elasticsearch plugins] ********************
task path: ansible-playbooks/roles/ansible-elasticsearch/tasks/elasticsearch-plugins.yml:23
basic
skipping: [elk.xx.org] => (item= No plugin detected)  => {"changed": false, "item": " No plugin detected", "skip_reason": "Conditional check failed", "skipped": true}

TASK [ansible-elasticsearch : Install elasticsearch plugins] *******************
task path: ansible-playbooks/roles/ansible-elasticsearch/tasks/elasticsearch-plugins.yml:34
basic
skipping: [elk.xx.org] => (item={u'version': u'latest', u'plugin': u'mobz/elasticsearch-head'})  => {"changed": false, "item": {"plugin": "mobz/elasticsearch-head", "version": "latest"}, "skip_reason": "Conditional check failed", "skipped": true}
skipping: [elk.xx.org] => (item={u'version': u'latest', u'plugin': u'lmenezes/elasticsearch-kopf'})  => {"changed": false, "item": {"plugin": "lmenezes/elasticsearch-kopf", "version": "latest"}, "skip_reason": "Conditional check failed", "skipped": true}
```

**Comment by barryib** [comment] 2016-09-07 13:24
@bhcopeland what is your ansible version? Are your running the **v2.0**, as mentioned in the your [gist](https://gist.github.com/b6ca5e3f3ee93c5a15f211e399018a28)? I googled quickly and found this on this [issue](https://github.com/ansible/ansible/issues/14438).

If yes, is it possible to update your ansible the latest version (2.1 I think) and see if it fixes your problem?

**Comment by bhcopeland** [comment] 2016-09-07 14:01
Thanks for looking into the issue @barryib . I am on [ansible 2.1.1  ](https://www.archlinux.org/packages/community/any/ansible/)

**Comment by barryib** [comment] 2016-09-07 14:36
@bhcopeland what's bordering is the ``"skip_reason": "Conditional check failed"`` with no output from the launched command.

Was you running ansible-playbook with at least (3 v) ``-vvv``?

**Comment by bhcopeland** [comment] 2016-09-07 14:42
@barryib , yup, actually 4 ;). Although, more than 3 doesn't make any difference, I just do 4 from habit. 

```ansible-playbook -i hosts --diff elk.yml --tags=plugins -vvvv``` Was the command I ran.

**Comment by barryib** [comment] 2016-09-07 14:50
@bhcopeland mmm... From this [line](https://github.com/elastic/ansible-elasticsearch/blob/master/tasks/elasticsearch-plugins.yml#L42) we can see that ``es_plugins_reinstall`` should be set to true for plugin installation. Sounds weird.

Can you try that one please?

**Comment by bhcopeland** [comment] 2016-09-07 15:08
okay set. 

```
skipping: [elk.xx.org] => (item={u'version': u'latest', u'plugin': u'mobz/elasticsearch-head'})  => {"changed": false, "item": {"plugin": "mobz/elasticsearch-head", "version": "latest"}, "skip_reason": "Conditional check failed", "skipped": true}
skipping: [elk.xx.org] => (item={u'version': u'latest', u'plugin': u'lmenezes/elasticsearch-kopf'})  => {"changed": false, "item": {"plugin": "lmenezes/elasticsearch-kopf", "version": "latest"}, "skip_reason": "Conditional check failed", "skipped": true}
```

My nick is bcc on freenode, if that helps.

**Comment by barryib** [comment] 2016-09-07 22:05
@bhcopeland Sorry for my late answer. 

Can you please comment this [line](https://github.com/elastic/ansible-elasticsearch/blob/master/tasks/elasticsearch-plugins.yml#L5) on the elasticsearch-plugin.yml and set ``es_plugins_reinstall`` to true before running your playbook? I think that the plugin installation is skipped because [``es_plugins_reinstall=false``](https://gist.github.com/bhcopeland/b6ca5e3f3ee93c5a15f211e399018a28#L142). You're using plugin tag, so with [this set_fact](https://github.com/elastic/ansible-elasticsearch/blob/master/tasks/elasticsearch-plugins.yml#L5):
- elasticsearch_install_from_package is defined and elasticsearch_install_from_repo.changed == **false**
- elasticsearch_install_from_package is defined and elasticsearch_install_from_package.changed == **false**
- es_plugins is not defined == **false**
- es_plugins is none == **false**

**Comment by bhcopeland** [comment] 2016-09-08 15:56
Thanks for the reply!

Right, so I commented out that [line](https://github.com/elastic/ansible-elasticsearch/blob/master/tasks/elasticsearch-plugins.yml#L5) and now the plugin installs. 

So, even know I had es_plugins_reinstall: true set in my playbook it's not installing. I will try and debug more tomorrow.

**Comment by bery** [comment] 2016-09-09 12:16
I have exactly the new issue since the latest release - seems that conditional checks fail if plugins are not installed and setting `es_plugins_reinstall` to true did not help

**Comment by barryib** [comment] 2016-09-09 13:13
@bhcopeland @bery I submitted [this](https://github.com/elastic/ansible-elasticsearch/pull/151) PR to solve your problem. Can you please review and see if it solves your problem?

Cheers.

**Comment by gingerwizard** [comment] 2016-09-12 08:57
Sorry late the party been off. I'll try and reproduce this today and add a test.  If @barryib fixes and all tests pass we'll merge.

**Comment by bhcopeland** [comment] 2016-09-12 09:26
thanks for your PR barry. I commented in the PR, it seems to work okay, only issue I saw was setting es_plugins_reinstall now makes no difference.

**Comment by barryib** [comment] 2016-09-13 16:42
@gingerwizard @bhcopeland I that this is a regression introduced by this commit 53535241370db11c77fac379f547f65fb49b1a13. See this [line](https://github.com/elastic/ansible-elasticsearch/commit/53535241370db11c77fac379f547f65fb49b1a13#diff-3f419eb05dd0502a4e53b27340029a92L5).

In that previous version, we only set ``es_plugins_reinstall`` to true when one of these following statements are true:
- ``elasticsearch_install_from_repo.changed`` - for plugins update
- ``elasticsearch_install_from_package.changed`` - for plugins update
- ``es_plugins`` is none - for plugins removal

In other way, you can explicitly set ``es_plugins_reinstall`` to false to avoid plugins reinstallation if nothing need to be updated.

**Comment by babadofar** [comment] 2016-09-15 07:32
Not sure if this is helpful information, but this bug hits me as well ;)

**Comment by gingerwizard** [comment] 2016-09-19 12:02
Yes recognised issue. https://github.com/elastic/ansible-elasticsearch/pull/154 to fix.

**Comment by gingerwizard** [comment] 2016-09-19 12:48
Closing @babadofar should be resolved.  Thanks for finding.

**Closed by gingerwizard** 2016-09-19 12:48 UTC
Labels: bug

**Comment by Thermi** [comment] 2016-10-03 20:08
I hit this today. I thought this was fixed?
#163

**Comment by michaeljoshuataylor** [comment] 2016-12-14 14:45
I ran into this issue over the weekend as well. Is there any new information about a resolution?

Additionally, post installation if I try to install a plugin manually, the path to /etc/default/[node_name]_elasticsearch is not set in the /usr/share/elasticsearch/bin/plugin script. This was using 2.4.0.

@gingerwizard

**Comment by Thermi** [comment] 2016-12-15 22:05
@michaeljoshuataylor As far as I am aware, that is not supported. You are supposed to use ansible-elasticsearch to install plugins.

**Comment by michaeljoshuataylor** [comment] 2016-12-22 02:02
@Thermi I made a symlink from my homedir to the official ansible-elasticsearch repo in /etc/ansible/roles/elasticsearch

**Comment by Thermi** [comment] 2016-12-22 09:45
@michaeljoshuataylor And how is that supposed to help with installing plugins?

**Comment by hatdropper1977** [comment] 2017-08-02 14:57
@Thermi   
> You are supposed to use ansible-elasticsearch to install plugins.

This fixed it for me, thanks.

**Comment by hatdropper1977** [comment] 2017-08-02 15:33
@Thermi  and others.  To be clear, I had to add the following elements to the vars stanza:

```yaml
 vars:
    es_enable_xpack: true
    es_api_basic_auth_username: elastic
    es_api_basic_auth_password: changeme
```

If I attempted to use the plugin module, ansible would install and then remove x-pack,

i.e the following **DOES NOT** work

```yaml
es_plugins:
    - plugin: x-pack
```
I believe this is due to [the x-pack task](https://github.com/elastic/ansible-elasticsearch/blob/master/tasks/xpack/elasticsearch-xpack-install.yml) which reads:

>  #Remove X-Pack if installed and its not been requested or the ES version has changed

**Comment by pemontto** [comment] 2017-11-23 15:40
Ran into this overriding es_enable_xpack while not installing any plugins.
This will fail
`-e "es_enable_xpack=false"`

This will skip x-pack tasks correctly
`-e "es_enable_xpack="`
