### ISSUE TITLE
How do you add custom scripts/templates?

### ISSUE THREAD

**Issue by strootman** [elastic/ansible-elasticsearch#57] opened 2016-01-21 20:45 UTC
The copy commands in the tasks/elasticsearch-scripts.yml and tasks/elasticsearch-templates.yml are pretty clear in their intent. 

So, is the expectation that I should clone this repo, and add any custom scripts/templates to the appropriate directory in `files/`?

Is there a way to configure a playbook to reference a different directory to load scripts/templates from?

**Comment by gingerwizard** [comment] 2016-01-21 22:53
Hi @strootman thanks for raising.  Currently a local template directory isn't configurable in the role so yes you would add to files/.

There will be a follow up release very shortly however and i agree this should be configurable - likewise for script.  Will add. 
Thanks

**Comment by strootman** [comment] 2016-01-21 22:57
:+1: Thank you

**Comment by babadofar** [comment] 2016-02-03 11:21
The same goes for other config files, dictionaries, synonyms, hunspell etc. Or should this be handled separately?

**Comment by strootman** [comment] 2016-03-10 00:23
I submitted a PR for this. Please take a look :)

**Comment by gingerwizard** [comment] 2016-03-18 14:58
@strootman apologies ive been out for a while. checking now. thanks.

**Comment by gingerwizard** [comment] 2016-03-18 15:19
@strootman merged. Thanks for the input! Happy to close?

**Comment by strootman** [comment] 2016-03-18 16:32
Yes, I think so.
Quick question though. This repo is the first I've seen that uses kitchen.ci. I was curious as to your thoughts about it.

I'm not sure if this is the best forum for having this discussion :)

**Comment by gingerwizard** [comment] 2016-03-18 16:43
Hi Strootman,
I'll close the ticket thanks.
Re kitchen.ci - it has soo far proved sufficient and has allowed us to ensure we have some repeatable tests across different platforms and versions.  The main issue we know face its limitation re being able to run a ansible role multiple times over a container/image  - thus preventing us from effectively testing that roles is idempotent as well as checking it upgrades plugins/versions appropriately.

I would love to hear peoples opinions on alternatives.  Please start a ticket to discuss possible testing strategies if your interested.

Thanks again for the pull request!

**Closed by gingerwizard** 2016-03-18 16:43 UTC
Labels: enhancement

**Comment by strootman** [comment] 2016-03-18 16:47
Well, various `kitchen` commands take regex patterns. Maybe you could author a pair of _suites_ which are meant to be run together. Then you could execute with `kitchen test paired_test_suite*_[PLATFORM]`. The idea being that the second suite would re-run on the same host, cluster, node.

I haven't tried that out, but it seems possible.

**Comment by gingerwizard** [comment] 2016-03-18 16:58
Yes the issue is each kitchen test currently provisions a new docker container.  The above just runs multiple containers - we use this pattern ability to create the test matrix in jenkins. I'm not aware of any ability to ask it to reuse a container - happy to be educated though.

**Comment by strootman** [comment] 2016-03-18 17:10
Ugh.  You're right :( Moving discussion to other topic.
