### ISSUE TITLE
udpate-rc.d fails on Ubuntu with multiple nodes on the same machine

### ISSUE THREAD

**Issue by jgoodall** [elastic/ansible-elasticsearch#70] opened 2016-03-08 18:33 UTC
`/usr/sbin/update-rc.d` fails on Ubuntu (15.04):

```
fatal: [hostname]: FAILED! => {"changed": false, "failed": true, "msg": "Error when trying to enable node2_elasticsearch: rc=1 Synchronizing state for node2_elasticsearch.service with sysvinit using update-rc.d...\nExecuting /usr/sbin/update-rc.d node2_elasticsearch defaults\ninsserv: script node2_elasticsearch: service elasticsearch already provided!\ninsserv: exiting now!\nupdate-rc.d: error: insserv rejected the script header\n"}
```

`node2` is the `es_instance_name`. 

I believe the issue is related to the following line in the debian init script:

```
# Provides:          elasticsearch
```

Should that be something like this?

```
# Provides:          {{es_instance_name}}_{{default_file | basename}}
```

My playbook looks like this:

```
- hosts: elasticsearch
  vars:
    es_major_version: "2.x"
    es_version: "2.2.0"
    es_heap_size: "31g"
    es_max_open_files: 262140
    es_data_dir: "/elasticsearch/data"
    es_log_dir: "/elasticsearch/log"
  roles:
    - { role: elasticsearch, es_instance_name: "node1", es_config: { node.name: "node1", http.port: 9200, transport.tcp.port: 9300, cluster.name: "cluster", bootstrap.mlockall: true, discovery.zen.ping.multicast.enabled: false } }
    - { role: elasticsearch, es_instance_name: "node2", es_config: { node.name: "node2", http.port: 9201, transport.tcp.port: 9301, discovery.zen.ping.unicast.hosts: "localhost:9300", cluster.name: "cluster", bootstrap.mlockall: true, discovery.zen.ping.multicast.enabled: false } }
    - { role: elasticsearch, es_instance_name: "node3", es_config: { node.name: "node3", http.port: 9202, transport.tcp.port: 9302, discovery.zen.ping.unicast.hosts: "localhost:9300", cluster.name: "cluster", bootstrap.mlockall: true, discovery.zen.ping.multicast.enabled: false } }
```

(I assume this is also an issue on redhat, but dont have a system to test.)

**Comment by jakommo** [comment] 2016-03-09 09:52
Thanks @jgoodall for reporting this. 

We currently only test against ubuntu `14.04`, as it is an LTS release, and I was not able to reproduce on there, but I'm able to reproduce on 15.04.

I think it might be related to the switch from `upstart` to `systemd` that was introduced in `15.04` and I assume `update-rc.d` is just a wrapper for `systemctl enable` now.

Thanks for the proposed change, applying `# Provides:          {{es_instance_name}}_{{default_file | basename}}` solved the issue on `15.04` for me.

Do you want to provide an PR (would require you to sign the [CLA](https://www.elastic.co/contributor-agreement))? Otherwise I would create one.

Just out of curiosity, what is the reason for running on `15.04`, as it is not an `LTS` release and already `EOL` since Feb 4 2016?

**Comment by jgoodall** [comment] 2016-03-09 13:22
Ah, @jakommo - you are definitely right. I had forgotten about the switch to `systemd`. I didnt set up the machine, so didnt pick the OS (would have put 14.04 on it). Just went back and looked, and I dont think my proposed change is the best approach (it solves the problem, but isnt the best solution). I think the right approach is to use the `systemd` configuration. Would a better approach be to use the `systemd` configuration file instead of the init script?

Actually, looking at `elasticsearch-config.yml` I think maybe the problem is it is putting startup scripts in both `/etc/init.d` and `/usr/lib/systemd/system`. I dont know the precedence order for it, but I think the fix is to add a conditional to check on the copy init files for an instance for redhat or debian to see if `use_system_d` is set, and not copy them then.

Does that sound right?

**Comment by jakommo** [comment] 2016-03-09 21:55
@jgoodall good point. I did some tests on ubuntu 16.04 today and:

* After reverting the change back to `# Provides: elasticsearch` the issue also appears on 16.04
* Trying to manually enable it with systemd results in 
```
root@2b80abeb50cb:~# systemctl enable node2_elasticsearch 
node2_elasticsearch.service is not a native service, redirecting to systemd-sysv-install
Executing /lib/systemd/systemd-sysv-install enable node2_elasticsearch
insserv: script node2_elasticsearch: service elasticsearch already provided!
insserv: exiting now!
update-rc.d: error: insserv rejected the script header
```
* After removing the init.d script, it works
```
root@2b80abeb50cb:~# rm /etc/init.d/node2_elasticsearch 
root@2b80abeb50cb:~# systemctl enable node2_elasticsearch 
Created symlink /etc/systemd/system/multi-user.target.wants/node2_elasticsearch.service, pointing to /usr/lib/systemd/system/node2_elasticsearch.service.
```

It seems like there is still some wrapper for upstart in place, that does some checks if a init script is available an then results in that error.

Your suggestion sounds right to me. I will setup an ubuntu 16.04 vm to do some real testing in the next days. (Just used docker for this and there is no real systemd in the docker containers IIRC) 

@gingerwizard whats your opinion on that?

**Comment by gingerwizard** [comment] 2016-03-18 16:31
@jakommo @jgoodall So i encountered this issue today on Debian 7 which uses init.d, when testing with 2 nodes on a machine. The Provides change i believe is necessary - i will make this change as part of a larger pull request today.

Additionally, i agree we shouldn't copy the init.d script or systemd scripts unnecessarily.  Currently the decision is made via:

- set_fact: use_system_d={{(ansible_distribution == 'Debian' and ansible_distribution_version | version_compare('8', '>=')) or (ansible_distribution == 'CentOS' and ansible_distribution_version | version_compare('7', '>=')) or (ansible_distribution == 'Ubuntu' and ansible_distribution_version | version_compare('15', '>=')) }}

The issue is we always copy the init script.  I will raise a separate issue for this and may also merge today.

**Comment by gingerwizard** [comment] 2016-03-18 19:36
Fixed in pull request [74](https://github.com/elastic/ansible-elasticsearch/pull/74)

**Closed** 2016-03-21 17:55 UTC
Labels: bug
