### ISSUE TITLE
Upgrade the Debian package seems broken

### ISSUE THREAD

**Issue by jlecour** [elastic/ansible-elasticsearch#145] opened 2016-09-01 09:37 UTC
Hi,

I've been testing the Ansible role for Elasticsearch and found an issue.
I'm using a Vagrant VM (with the "debian/jessie64" base image) instead of a Docker container.
I execute the playbook with just a node and cluster names configured.

The first time, I get a working cluster. The second time (without changing anything) it still works with no "changed" status, which is intended.

When I upgrade the ES version (2.3.4 → 2.4.0) the SystemD part fails silently (no error reported by Ansible).

Instead of updating the service file, I get a (sort of) duplicate : the previous (working) service AND the original file from the package (which SystemD sees as the proper file) : 

```
# ls -l /usr/lib/systemd/system/
total 8
-rw-r--r-- 1 root root 1803 Aug 29 09:24 elasticsearch.service.dpkg-dist
-rw-r--r-- 1 root root 1720 Sep  1 09:17 node1_elasticsearch.service
```

After this upgrade, the SystemD unit is not working properly : status is inconsistent, stop is inefficient, and after a kill, the start operation starts a default cluster (not using the instance-specific configuration).

**Comment by gingerwizard** [comment] 2016-09-01 09:48
There is no test for this currently.  It should work and we need to reproduce with the kitchen tests.  Prioritizing as this is important. @jlecour @jakommo

**Comment by jlecour** [comment] 2016-09-01 09:58
I'm sorry, I have 0 experience with kitchen. I'll take a look and will report results if I get to an interesting point.

Thanks a lot for maintaining this playbook. It's very useful.

**Comment by gingerwizard** [comment] 2016-09-02 12:31
@jlecour no worries im adding some more tests for shield+idempotence so will include a test + fix in the PR

**Comment by jakommo** [comment] 2016-09-08 20:57
Hi @jlecour I tested this today with a debian jessie EC2 instance and I'm kind of able to reproduce.
I also end up with that `elasticsearch.service.dpkg-dist` but all operations with `systemctl * node1_elasticsearch.service` work for me. I tried start, stop, restart and status and it works as expected.

Could you post the playbook you used and elaborate on the error you got?

About the `dpkg-dist` file, we only remove the `elasticsearch.service` [file](https://github.com/elastic/ansible-elasticsearch/blob/master/tasks/elasticsearch-config.yml#L66)
Looks like the ansible file module does not support wildcards (for good reasons), so we might need to think about removing this file explicitly and also [adjust the tests](https://github.com/elastic/ansible-elasticsearch/search?l=ruby&q=%22elasticsearch.service%22&type=Code&utf8=%E2%9C%93).

I was under the impression that `.dpkg-dist` only get created if the original file changed but the file being removed also seems to apply.

**Comment by jakommo** [comment] 2016-09-21 13:15
@jlecour any update on this:

> Could you post the playbook you used and elaborate on the error you got?

Otherwise I close this as it seems to work fine when using the unit file provided by the role

**Comment by gingerwizard** [comment] 2016-09-21 13:17
I'll add https://github.com/elastic/ansible-elasticsearch/issues/160 today. If tests pass we will a playbook as @jakommo highlights

**Comment by jakommo** [comment] 2016-09-28 16:42
Closing due to lack of response.

**Closed by jakommo** 2016-09-28 16:42 UTC
