### ISSUE TITLE
Stuck on task: "Wait for elasticsearch to startup"

### ISSUE THREAD

**Issue by aldee07** [elastic/ansible-elasticsearch#333] opened 2017-07-12 06:22 UTC
Using this minimal playbook configuration/definition...

```
---
- name: ES
  hosts: local
  vars:
    es_start_service: true
  roles:
    - role: elasticsearch
      es_instance_name: "node1"
      es_config: { http.port: 9200 }
```
always ends up to a Connection Timeout problem. 

I also tried this suggestion https://discuss.elastic.co/t/ubuntu-16-04-ansible-elasticsearch-stuck-at-wait-for-elasticsearch-to-startup/83338/7 but to no luck.

**Comment by aldee07** [comment] 2017-07-12 09:42
Okay. I think I managed to fix my issue. This was my case: 

I was running ElasticSearch in a VM (vagrant - ubuntu 16.04) which has **1GB** of memory allocated. By default, this ansible role allocates [**2GB**](https://github.com/elastic/ansible-elasticsearch/blob/master/templates/jvm.options.j2#L24) for the heap size. This [stackoverflow answer](https://stackoverflow.com/a/41662868/969645) points out the issue.

Setting the **es_heap_size** in `vars` section lesser than the allocated memory of the VM fixed the issue.

**Comment by barryib** [comment] 2017-08-15 22:41
@aldee07 Maybe similar to https://github.com/elastic/ansible-elasticsearch/issues/305

**Comment by gingerwizard** [comment] 2017-08-17 09:15
Hopefully resolved by https://github.com/elastic/ansible-elasticsearch/pull/358. I was also able to reproduce but not with the changes.

**Comment by gingerwizard** [comment] 2017-08-18 23:05
I believe this will be resolved when we address https://github.com/elastic/ansible-elasticsearch/issues/305. Marking as duplicate. #358  also should be helped here

**Closed by gingerwizard** 2017-08-18 23:05 UTC
Labels: bug, duplicate

**Comment by nagyobbaron** [comment] 2022-01-12 08:20
Maybe there is a fix for this issue:
the problem is in elastic.elasticsearch/tasks/mainl.ym - line 71
"wait_for: host={{ es_api_host }} port={{ es_api_port }} delay=5 connect_timeout=1"
The es_api_host is translated to "localhost" therefore tha task is exited with 1.
if you define the "es_api_host" variable in your playbook the play will pass the task.
