### ISSUE TITLE
Issues while installing a single elasticsearch node

### ISSUE THREAD

**Issue by pcamelo** [elastic/ansible-elasticsearch#626] opened 2019-10-30 15:10 UTC
**Elasticsearch version**: 7.4.0

**Role version**:  7.4.0 (aff478f52f5976ac88bac4e940c9123b351f8048)

**JVM version**:
```/usr/share/elasticsearch/jdk/bin# ./java -version
openjdk version "13" 2019-09-17
OpenJDK Runtime Environment AdoptOpenJDK (build 13+33)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 13+33, mixed mode, sharing)
```

**OS version**:  Ubuntu Server 18.04.3 LTS
```
Linux XXXX 4.15.0-66-generic #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Description of the problem including expected versus actual behaviour**:

When I try to setup a single ElasticSearch instance it fails to start after restarting with config from ansible role.

**Playbook**:

```
- role: elastic.elasticsearch
  vars:
    es_version: 7.4.0
    es_config:
      network.host: 0.0.0.0
      discovery.seed_hosts: []
      logger.org.elasticsearch.cluster.coordination.ClusterBootstrapService: TRACE
      logger.org.elasticsearch.discovery: TRACE
    es_heap_size: 16g
```

**Ansible Logs**:
No relevant errors are thrown with the above config. However I can provide those if they are relevant for troubleshooting.

**ES Logs**:

```[2019-10-30T15:04:48,634][TRACE][o.e.d.PeerFinder         ] [XXXX] startProbe(192.168.xxx.xxx:9300) not probing local node
[2019-10-30T15:04:48,634][TRACE][o.e.d.PeerFinder         ] [XXXX] probing resolved transport addresses []
[2019-10-30T15:04:49,635][TRACE][o.e.d.PeerFinder         ] [XXXX] probing master nodes from cluster state: nodes:
   {XXXX}{XXXXXXXXXXXXXXXX}{XXXXXXXXXXXXXXXX}{192.168.xxx.xxx}{192.168.xxx.xxx:9300}{ilm}{ml.machine_memory=33716301824, xpack.installed=true, ml.max_open_jobs=20}, local

[2019-10-30T15:04:50,598][WARN ][o.e.c.c.ClusterFormationFailureHelper] [XXXX] master not discovered yet, this node has not previously joined a bootstrapped (v7+) cluster, and [cluster.initial_master_nodes] is empty on this node: have discovered [{XXXX}{XXXXXXXXXXXXXXXX}{XXXXXXXXXXXXXXXX}{192.168.xxx.xxx}{192.168.xxx.xxx:9300}{ilm}{ml.machine_memory=33716301824, xpack.installed=true, ml.max_open_jobs=20}]; discovery will continue using [] from hosts providers and [{XXXX}{XXXXXXXXXXXXXXXX}{XXXXXXXXXXXXXXXX}{192.168.xxx.xxx}{192.168.xxx.xxx:9300}{ilm}{ml.machine_memory=33716301824, xpack.installed=true, ml.max_open_jobs=20}] from last-known cluster state; node term 0, last-accepted version 0 in term 0
[2019-10-30T15:04:50,605][WARN ][o.e.n.Node               ] [XXXX] timed out while waiting for initial discovery state - timeout: 30s
```

**ES Configuration**:
```
discovery.seed_hosts: []
logger.org.elasticsearch.cluster.coordination.ClusterBootstrapService: TRACE
logger.org.elasticsearch.discovery: TRACE
network.host: 0.0.0.0


cluster.name: elasticsearch

node.name: XXXX

#################################### Paths ####################################

# Path to directory containing configuration (this file and logging.yml):

path.data: /var/lib/elasticsearch

path.logs: /var/log/elasticsearch


action.auto_create_index: true
```

**Comment by jmlrt** [comment] 2019-10-30 15:53
Hi @pcamelo, 
I think that `discovery.seed_hosts: []` line in your `es_config` maybe the cause of your problem.
Did you try without this line?

```
- role: elastic.elasticsearch
  vars:
    es_version: 7.4.0
    es_config:
      network.host: 0.0.0.0
      logger.org.elasticsearch.cluster.coordination.ClusterBootstrapService: TRACE
      logger.org.elasticsearch.discovery: TRACE
    es_heap_size: 16g
```

**Comment by jmlrt** [comment] 2019-10-30 18:16
Elasticsearch production mode when setting `network.host` to a a different value than `localhost` id partly doccumented [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/network.host.html) and [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/system-config.html#dev-vs-prod).

I'm closing the issue as this is not related to the ansible role.

**Closed by jmlrt** 2019-10-30 18:16 UTC
